language: php
dist: xenial
php:
  - "7.2"

services:
  - docker
  - mysql

before_install:
  - bash ./build/travis/sonarqube.sh
  - npm install -g bower
  - composer self-update
  - mysql -e 'CREATE DATABASE concerto_test;'

install:
  - composer install --no-interaction
  - cd $TRAVIS_BUILD_DIR/src/Concerto/PanelBundle/Resources/public/angularjs && bower install --allow-root
  - cd $TRAVIS_BUILD_DIR/src/Concerto/TestBundle/Resources/public/angularjs && bower install --allow-root
  - cd $TRAVIS_BUILD_DIR
  - bash ./build/travis/docker_build.sh

script: docker-compose -f ./build/travis/docker-compose.yml up --build --exit-code-from concerto

deploy:
  provider: script
  script: bash ./build/travis/docker_deploy.sh
  on:
    all_branches: true
