version: '3.0'
services:
    concerto:
      build: .
      container_name: concerto
      restart: unless-stopped
      environment:
        - DB_TEST_HOST=127.0.0.1
        - DB_TEST_PORT=3306
        - DB_TEST_NAME=concerto_test
        - DB_TEST_USER=root
        - DB_TEST_PASSWORD=
        - PHP_FPM_PM=dynamic
        - PHP_FPM_PM_MAX_CHILDREN=30
        - PHP_FPM_PM_START_SERVERS=10
        - PHP_FPM_PM_MIN_SPARE_SERVERS=5
        - PHP_FPM_PM_MAX_SPARE_SERVERS=15
        - PHP_FPM_PM_PROCESS_IDLE_TIMEOUT=10s
        - PHP_FPM_PM_MAX_REQUESTS=300
        - TZ=Europe/London
      network_mode: host