version: '3.0'
services:
    database:
      image: mysql:5.7
      container_name: database
      restart: unless-stopped
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=concerto
        - TZ=Europe/London
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./logs/database:/var/log/mysql

    concerto:
      image: campsych/concerto-platform:master
      container_name: concerto
      restart: unless-stopped
      volumes:
        - ./data/concerto:/data
      environment:
        - DB_HOST=database
        - DB_PORT=3306
        - DB_NAME=concerto
        - DB_USER=root
        - DB_PASSWORD=root
        - PHP_FPM_PM=dynamic
        - PHP_FPM_PM_MAX_CHILDREN=30
        - PHP_FPM_PM_START_SERVERS=10
        - PHP_FPM_PM_MIN_SPARE_SERVERS=5
        - PHP_FPM_PM_MAX_SPARE_SERVERS=15
        - PHP_FPM_PM_PROCESS_IDLE_TIMEOUT=10s
        - PHP_FPM_PM_MAX_REQUESTS=300
        - TZ=Europe/London
      ports:
        - "80:80"
